spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
#mybatis配置
mybatis:
  # 特别注意新增的两行与configuration要对齐!!!
  typeAliasesPackage: edu.scau.mis.pos.domain
  mapperLocations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
