server:
  port: 8081

aliyun:
  oss:
    endpoint: http://oss-cn-guangzhou.aliyuncs.com
    accessKeyId: 1958657896447928
    accessKeySecret: xjwgj72808
    bucketName: uml-web-images-2025
spring:
  devtools:
    restart:
      enabled: true
  # 数据源
  datasource:
    # 连接池hikari
    type: com.zaxxer.hikari.HikariDataSource
    # 驱动程序
    driverClassName: com.mysql.cj.jdbc.Driver
    # 连接参数
    url: jdbc:mysql://localhost:3306/isdp-db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Xj+LFz72808